# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SubWindowDicts.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dictionaries(object):
    def setupUi(self, Dictionaries):
        Dictionaries.setObjectName("Dictionaries")
        Dictionaries.resize(415, 304)
        self.gridLayout = QtWidgets.QGridLayout(Dictionaries)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(Dictionaries)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dictionaries)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButtonAdd = QtWidgets.QPushButton(Dictionaries)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.gridLayout.addWidget(self.pushButtonAdd, 0, 3, 1, 1)
        self.pushButtonEdit = QtWidgets.QPushButton(Dictionaries)
        self.pushButtonEdit.setObjectName("pushButtonEdit")
        self.gridLayout.addWidget(self.pushButtonEdit, 0, 4, 1, 1)
        self.tableView = QtWidgets.QTableView(Dictionaries)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 4, 0, 4, 5)
        self.pushButton_3 = QtWidgets.QPushButton(Dictionaries)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 3, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(Dictionaries)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 4, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Dictionaries)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 8, 0, 1, 2)
        self.pushButton_5 = QtWidgets.QPushButton(Dictionaries)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 8, 2, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(Dictionaries)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout.addWidget(self.comboBox_2, 1, 1, 1, 2)
        self.comboBox = QtWidgets.QComboBox(Dictionaries)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 2)
        self.pushButton_2 = QtWidgets.QPushButton(Dictionaries)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 8, 3, 1, 1)

        self.retranslateUi(Dictionaries)
        QtCore.QMetaObject.connectSlotsByName(Dictionaries)

    def retranslateUi(self, Dictionaries):
        _translate = QtCore.QCoreApplication.translate
        Dictionaries.setWindowTitle(_translate("Dictionaries", "Games"))
        self.label_2.setText(_translate("Dictionaries", "Columns"))
        self.label.setText(_translate("Dictionaries", "Rows"))
        self.pushButtonAdd.setText(_translate("Dictionaries", "Add"))
        self.pushButtonEdit.setText(_translate("Dictionaries", "Edit"))
        self.pushButton_3.setText(_translate("Dictionaries", "Add"))
        self.pushButton_4.setText(_translate("Dictionaries", "Edit"))
        self.pushButton.setText(_translate("Dictionaries", "Refresh"))
        self.pushButton_5.setText(_translate("Dictionaries", "Switch"))
        self.pushButton_2.setText(_translate("Dictionaries", "Details"))
